stages:
  prepare:
    cmd: python src/prepare_house.py --params params.yaml
    deps:
      - data/house_price_pakistan.csv
      - src/prepare_house.py
    params:
      - prepare
    outs:
      - data/cleaned_house_data.csv

  features:
    cmd: python src/features_house.py --params params.yaml
    deps:
      - data/cleaned_house_data.csv
      - src/features_house.py
    params:
      - prepare
      - features
    outs:
      - data/X_train.npy
      - data/X_test.npy
      - data/y_train.npy
      - data/y_test.npy
      - models/label_encoders.pkl
      - models/model_features.pkl
      - models/feature_field_map.pkl

  train:
    cmd: python src/train_house.py --params params.yaml
    deps:
      - data/X_train.npy
      - data/y_train.npy
      - src/train_house.py
      - models/model_features.pkl
    params:
      - train
    outs:
      - models/house_price_model.pkl

  evaluate:
    cmd: python src/evaluate_house.py --params params.yaml
    deps:
      - models/house_price_model.pkl
      - data/X_test.npy
      - data/y_test.npy
      - src/evaluate_house.py
    params:
      - evaluate
    metrics:
      - metrics/eval.json:
          cache: false
